skills = [
    'microsoft office',
    'word',
    'excel',
    'powerpoint',
    'outlook',
    'access',
    'onenote',
    
    'email',
    'filter',
    'folder',
    'mail merge',
    'rules',

    'google drive',
    'docs',
    'sheets',
    'forms',
    'slides',

    'writing',
    'wordpress',
    'seo',
    'yoast',
    'journalism',
    'technical writing',
    'ghostwriting',

    'spreadsheet',
    'openoffice',
    'comparative analyses',
    'pivot table',
    'macro',
    'vlookup',
    'database',

    'social media',
    'facebook',
    'twitter',
    'linkedin',
    'instagram',
    'customer interaction',

    'productivity',
    'trello',
    'slack',
    'asana',
    'todoist',
    'zapier',
    'basecamp',
    'git',

    'invoicing',
    'expense tracking',
    'accounts payable',
    'reports',
    'payroll',
    'cashflow',

    'graphical',
    'photoshop',
    'illustrator',
    'adobe',
    'acrobat',
    'indesign',
    'free hand',
    'corel draw',

    'math',
    'algorithm',
    'arithmetic',
    'statistic',
    'algebra',
    'calculus'

    'web',
    'html',
    'html5',
    'css',
    'django',
    'node.js',
    'lavarel',
    'react',
    'cms',
    'content management',
    
    'programming',
    'c#',
    'java',
    'c++',
    'javascript',
    'python',
    'php',
    'objective-c',
    'ajax',
    'asp.net',
    'ruby',
    'golang',
    'sas',
    'r',
    'xml',
    'vba',
    'sql',
    'postgres',
    'mysql',

    
    'blockchain',
    'bitcoin',
    'ripple',
    'ethereum',
    'bch',
    'monero',
    'litecoin',
    
    'cloud',
    'distributed computing',
    'kubernetes',
    'docker',
    'azure',
    'aws',
    
    'machine learning',
    'deep learning',
    'reinforcement learning',
    'nlp',
    'natural language'
    'tensorflow',
    'keras',
    'scikitlearn',
    'google cloud',
    'ml engine',
    'AML',
    'numpy',
    'scipy',
    
    'operating system',
    'windows',
    'macos',
    'linux'
    
    'network',
    'information security',
    'oscp',
    'cissp',
    'ccna',
    'ceh',
    'comptia',
    
    'engineering',
    'autocad',
    'matlab',
    'verilog',
    'simulink',
    'pspice',
    'multisim',
    'etap',
    
    'virtualization',
    'mware',
    'vsphere',
    'hyper-v',
    'qemu',
    'oracle',
    'virtualbox',
    'xen',
    
    'big data',
    'statistical analysis',
    'data analysis',
    'data mining',
    'modeling',
    'database management',
    'hadoop',
    'spark',
    'pandas',
    'relational database',
    'graph database',
    
    'ecommerce',
    'magento',
    'prestashop',
    'joomla',
    'opencart',
    'woocommerce',
    'shopify',
    'salesforce'
    
    'decision making',
    'forecasting',
    'cashflow',
    'risk management',
    'delegation',
    'scrum',

    'agile',
    'lean',
    'devops',
    'ci/cd'
]
    